apiVersion: v1
kind: Service
metadata:
  name: v1-echo-svc
spec:
  type: NodePort
  selector:
    app: v1-echo
  ports:
  - name: https
    protocol: TCP
    port: 8090
    targetPort: 8090
    nodePort: 30100