apiVersion: apps/v1
kind: Deployment
metadata:
  name: v2-echo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: v2-echo
  template:
    metadata:
      labels:
        app: v2-echo
    spec:
      containers:
      - name: v2-echo-container
        image: pranoyk/echo_v2:1.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8090